### ISSUE TITLE
Plannung Datenbank

### ISSUE THREAD

**Issue by janbellenberg** [janbellenberg/mobiler-luftqualitaetsmesser#5]
Plannung der Datenbank (DB-Modell)

Benötigte Tabellen:
- Gebäude
- Räume
- Positionen
- Messungen (Co2, Feuchte, Temperatur, Timestamp)

**Comment by OmarAk312** [comment]
Hallo Jan

**Comment by alfredlehmann** [comment]
Das ist ein Test-comment

**Comment by OmarAk312** [comment]
[ER-Modell_Mobiler_Luftqualitätsmesser.pdf](https://github.com/janbellenberg/mobiler-luftqualitaetsmesser/files/6668456/ER-Modell_Mobiler_Luftqualitatsmesser.pdf)
